services:
  ollama:
    build:
      context: ./ollama
    container_name: ollama

    ports:
      - "11434:11434"

    environment:
      - OLLAMA_THREADS=10    
      - OLLAMA_BATCH=512    
      - OLLAMA_CTX_SIZE=4096 

    volumes:
      - ollama-models:/root/.ollama/models

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: rag-backend
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434

  web:
    build:
      context: ./web
    container_name: rag-web
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  ollama-models:

